### ISSUE TITLE
Hello, I am not sure about the structure of this dataset, whether this code can only predict one key frame of the video or all frames of the video can be fed into the model for prediction

### ISSUE THREAD

**Issue by feililucky** [SimonZeng7108/Video-TransUNet#1]

**Comment by SimonZeng7108** [comment]
Hi,

The input data structure is formulated as B*T*C*H*W, where B is the batch size, T is the snippet size(number of frames), C is the image channel, H is the height and W is the width. This holds true for both training and inference. 
The model takes in multiple frames but only predicts the central frame, so if you want to predict the whole video, you will have to parse the video in the data structure format for each frame. 
Best,
Simon

**Comment by feililucky** [comment]
Hello, I input in the format [24, 3, 3, 112, 112] as you said, but an error was reported. The error was as follows: keyframe = x[:, int((x.shape[1]-1)/ 2), :, :].unsqueeze(1).repeat(1,3,1,1)
RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor.
 but no error is reported when I input it in the format of [24, 3, 112, 112],How can I solve this problem? Thank you very much for your help.

**Comment by SimonZeng7108** [comment]
Hi,

Sorry for the late reply.

Our data structure is slightly different than yours, as our dataset is grey scale x-ray images, and the input data is in the shape of BTHW, you will probably need to modify the original code according to yours. The other note is that the input data should also contain a ground truth.

Best,
Simon
