### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by feililucky** [SimonZeng7108/Video-TransUNet#2]
Hello, will you publish your data set? Thank you very much！

**Comment by SimonZeng7108** [comment]
Hi,

This paper contains work on the dataset provided by North Bristol NHS Trust with ethical approval by the University of Bristol[REF: 11277]. Unfortunately, the ethical review only grants usage and research publication purposes and does not include data publishment. Hence I regret to say we can not provide the whole dataset. 

However, we are happy to provide one anonymised data sample for you for research purposes only. Please provide us with an email in the comment.

best,

Simon
